### ISSUE TITLE
Installation Directory

### ISSUE THREAD

**Issue by dk009dk** [cargocultprog/alaterm#10]
Can i install alaterm in external sdcard or pendrive.

I haven't sufficient storage for install alaterm in internal storage.

Is it possible that i change the `$HOME,$PREFIX`
and other directory to external sdcard or pendrive ?
@cargocultprog

**Comment by dk009dk** [comment]
I already formatted my sdcard in ext3 linux system.

**Comment by cargocultprog** [comment]
In that case, it might work. Unverified.

In the version 2 installer (current), try modifying file v2installer/process/globals.bash. Variable alatermTop must be modified. I do not know where your sdcard is located in Android. Try `cd /storage` and hunt through the choices. My own sdcard (not ext3) is device 0000-0000.

**Comment by dk009dk** [comment]
Thanks for your efforts.👍

**Comment by cargocultprog** [comment]
Let me know if it works. 

The current scripts detect free space onboard, even if you attempt to install to ext3 media. If you suceed, then I can modify that part. If no success, no modification.

In any case, the installer should be launched by Termux, from the media, rather than from Termux home.

**Comment by cargocultprog** [comment]
Further info: Even with a properly formatted media, it is very unlikely that you can install Alaterm there. The reason is that executation of external files is blocked by Android security, even if the media itself grants permissions. This is known to the Termux project, and mentioned on its FAQ page.

Indeed, you may not be able to write to external media, directly from Termux. As far as I know, you can only write to media by first copying (or moving) the file from Termux to Android shared storage, then (without Termux) using Android file manager to move or copy the file to external media.

It may be that case that even rooted devices will fail. But I do not provide support for root.
