### ISSUE TITLE
Can't run 00-alaterm.bash install

### ISSUE THREAD

**Issue by viniavila** [cargocultprog/alaterm#2]
This is my error message:

$ bash 00-alaterm.bash install
Performing preliminary checks on your Termux system...
Checking if Termux is up-to-date, and upgrading if necessary...
WARNING. Looks like your Internet is disconected.
Or server at github.com is down.
Wait awhile. Then enter when ready :
Trying again...
PROBLEM. Still no connection.
Check your Internet, wait, and try again later.
This script will now exit. Releasing Termux wakelock.

Obviously, my Internet connection is up and github has been accessed normally.

My device is a Galaxy S6 Tab, Android 10, DeX mode on

Thanks.

**Comment by cargocultprog** [comment]
I have Android 9, cannot upgrade to Android 10 until September. But I do not think that is the problem. I cannot debug in Dex mode. The current code was tested by me, and it worked OK for a fresh install on my machine.

Question 1: Can you update Termux by itself, without using the alaterm scripts? During this past week, there was a problem seen by some Termux users, depending on what they have installed in Termux. Especially affected xfce4 users. If you cannot update Termux by itself, then installing alaterm will also fail.

Question 2: In Termux. what happens if youy do this: ping github.com

**Comment by cargocultprog** [comment]
Download 00-alaterm.bash, version 1.1.3. Try again. Tell me what happened.

**Comment by cargocultprog** [comment]
The problem was a change in how the `ping` command responds. Fixed in version 1.1.3 and later.

**Comment by viniavila** [comment]
Problem Fixed. Thanks!
