### ISSUE TITLE
Does it work on armv7l?

### ISSUE THREAD

**Issue by jlscott0731** [cargocultprog/alaterm#4]
My Android is armv7l and I'm having so much trouble getting arch installed!

**Comment by cargocultprog** [comment]
My device is armv7l. No problem. Has worked for months. 

What is your device?

Does the alaterm installer tell you that your device fails preliminary check? If that is the case, then you are out of luck. Not because of armv7l, but some other reason.

Does the installer pass preliminary check, then fail later? If so, what does it say when it exits?

When did you download the installer? Version? 

I cannot help you unless you provide more details. Alaterm is known to work for a number of other users.

**Comment by jlscott0731** [comment]
My device is an LG Tribute Empire x220p. This device I'm finding out has
all sorts of restrictions on it. I'm also looking for a way to root it, but
I'm not getting very far with that either. Which is extremely dissatisfying
because Im a major device tweaker! To the point of getting rid of Android
completely.

On Jun 20, 2020 12:33 PM, "cargocultprog" <notifications@github.com> wrote:

My device is armv7l. No problem. Has worked for months.

What is your device?

Does the alaterm installer tell you that your device fails preliminary
check? If that is the case, then you are out of luck. Not because of
armv7l, but some other reason.

Does the installer pass preliminary check, then fail later? If so, what
does it say when it exits?

When did you download the installer? Version?

I cannot help you unless you provide more details. Alaterm is known to work
for a number of other users.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cargocultprog/alaterm/issues/4#issuecomment-647036991>,
or unsubscribe

**Comment by cargocultprog** [comment]
If your device has restrictions, then alaterm cannot defeat them.

When the installer script fails, what messages do you get when it exits?

**Comment by cargocultprog** [comment]
Your device would not meet specs. According to LG its processor is not fully compatible with ARM architecture. Also, it has a small screen, so alaterm would be of little benefit. In any case, alaterm only interects with non-phone functions.

Problem is not alaterm. Issue closed.
