### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by dk009dk** [cargocultprog/alaterm#5]
**device**
Redmi note 7
Android  9

**Exit message from alaterm script**
`$ bash 00-alaterm.bash install`
Performing preliminary checks on your Termux system...
00-alaterm.bash: line 324: 8.7: syntax error: invalid arithmetic operator (error token is ".7")
Downloading scripts from the alaterm repository at GitHub...
Got the scripts. Continuing...
Android may ask if you wish to stop optimizing battery usage.
You may allow or deny, but installation is faster if you allow.
This script will now exit. Releasing Termux wakelock.

 **Issue**
 before i click allow on on pop-up message script will exit.

I repeat installation process many times  but every time before i click allow on pop-up message script will exit.

**Comment by cargocultprog** [comment]
There are two possibilities. One is that your specific device is denying access to information. Although there is a work-around, I expect that there will be other, un-fixable issues that arise later.

Another possibility is that your device is reporting its free space in an unexpected format. If so, then this might help:
```
sed -i 's/.*datanumnum=.*/let datanumnum=5/g' 00-alaterm.bash
```
That changes the script so that it thinks you have sufficient free space, without measuring it. But if this also fails, it means your device security model is too tight, in which case I cannot help.

**Comment by dk009dk** [comment]
thanks 
👍👍
It's working.

**Comment by dk009dk** [comment]
Can we install kali linux or another linux distributions like this way  ?
Is it possible to install kali linux by changing this script ?

Thanks !!
