### ISSUE TITLE
It is not ISSUE

### ISSUE THREAD

**Issue by dk009dk** [cargocultprog/alaterm#6]
It's not a issue.

Can we install kali linux or another linux distributions like this way  ?
Is it possible to install kali linux by changing this script ?

 I am waiting for your reply !
Thanks !!

**Comment by cargocultprog** [comment]
Maybe, maybe not. It cannot be done by a simple modification to the alaterm scripts.

The first requirement is that the Linux distribution (in your case, Kali) be compiled for the ARM architecture. Apparently there does exist a "Kali Linux ARM" so maybe OK.

The second requirement is that the features you need are non-root, unless you have rooted your machine. But root is well beyond the scope of this project. If you have rooted your machine, then you might consider installing Linux so that it is directly bootable. I am told that this can be done, but I do not know how on handheld devices, and it may depend on your device model.

The third is that the features you need are not blocked by SELinux policies, or any other security, whether from Android or anywhere else. Again, outside the scope of this project.

Really, a handheld device is an inappropriate tool for the things that Kali does.

You might also have a look at the "TermuxArch" installation, by SDRausty. It uses the same Arch Linux ARM archive, but does not produce a graphical desktop. It is pre-configured for use with file server. It can be installed in parallel to alaterm,. since they do not occupy the same files or interact with each other.

**Comment by dk009dk** [comment]
Thanks for reply !
