### ISSUE TITLE
bad URL 

### ISSUE THREAD

**Issue by nikey02** [cargocultprog/alaterm#9]
**Describe the bug**

**Your device**
mi redmi note 8 

**Exit message from alaterm script**
![Screenshot_2020-08-31-19-00-57-167_com termux](https://user-images.githubusercontent.com/68458326/91728057-2e39a780-ebc0-11ea-8475-603ff7aeb380.jpg)

**Repeatable?**
may be

**Status file**
![Screenshot_2020-08-31-19-26-29-354_com termux](https://user-images.githubusercontent.com/68458326/91728222-6e992580-ebc0-11ea-8265-2819145ed5e9.jpg)

**Additional context**
i think `/` is missing 
packages are downloaded and exit but then 
i restart install script it download with above errors.

**Comment by cargocultprog** [comment]
Not a bug in Alaterm. The Arch Linux ARM repositories sometimes report bad URL . Often occurs. Re-run Alaterm. You can manually select a mirror, if necessary.

**Comment by cargocultprog** [comment]
Further info: You saw the list of packages, to be upgraded. That list comes from the pacman software, part of Arch. It means that the URL was good, at that point in time. But the list of packages does look like incorrect URL, missing slash, as you saw. That means the Arch list was written wrong, at the download mirror. There is nothing Alaterm can do about that, because Alaterm does not write the URL. You must wait until Arch Linux ARM project corrects the list.

**Comment by nikey02** [comment]
Thanks for your time and work.🙂

**Comment by nikey02** [comment]
Slash was missing in my file.
I have added.
